version: '3'
services:

  petclinic-dev:
    build: '.'
    ports:
    - '8080:8080'
    depends_on:
    - db-dev
    volumes:
    - './petclinic-dev/application.properties:/app/application.properties'
    environment:
      JAVA_OPTS: ''
    command: ["/app/./wait-for-it.sh", "db-dev:3306", "-s", "-t", "60", "--", "java", '${JAVA_OPTS}', "-jar", '/app/petclinic.jar', '--spring.config.location=/app/application.properties' ]
    networks:
    - petclinic-dev

  db-dev:
    image: mysql:5.7
    ports:
    - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: C4ngM3n0000w
      MYSQL_DATABASE: petclinic-dev
    volumes:
    - /opt/mysql-data-db-dev/:/var/lib/mysql
    networks:
    - petclinic-dev

networks:
  petclinic-dev:
    driver: bridge
